<%@ Page Language="C#" AutoEventWireup="true" CodeBehind="SqlDataSource.aspx.cs" Inherits="GameStore.Pages.SqlDataSource" %>

<!DOCTYPE html>

<html xmlns="http://www.w3.org/1999/xhtml">
<head runat="server">
<meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
    <title>GameStore</title>
</head>
<body>
    <form id="form1" runat="server">
         <asp:SqlDataSource ID="SqlDataSource1" runat="server" ProviderName="System.Data.SqlClient" 
            ConnectionString="<%$ ConnectionStrings:gridViewDBConnection %>" 
            SelectCommand="SELECT GameID, Name, Description, Category, Price FROM Games"

            UpdateCommand="UPDATE Games SET Name=@Name, Description=@Description, Category=@Category,
		Price=@Price FROM Games WHERE GameID=@original_GameID AND Name=@original_Name
		AND Description=@original_Description AND Category=@original_Category 
		AND Price=@original_Price" 
             DeleteCommand="DELETE Games WHERE GameID=@GameID"
             InsertCommand="INSERT INTO Games (Name,Description,Category,Price) VALUES (@Name, @Description, @Category, @Price)"
	            ConflictDetection="CompareAllValues"
        OldValuesParameterFormatString="original_{0}">
    </asp:SqlDataSource>

        <asp:DetailsView ID="detailsInsertEmployee" runat="server" DataSourceID="SqlDataSource1" DefaultMode="Insert" 
	AutoGenerateInsertButton="True" AutoGenerateRows="false" >
            <Fields>
                <asp:BoundField DataField="GameID" ReadOnly="True" InsertVisible="False" />
                <asp:BoundField DataField="Name" HeaderText="Name" />
                <asp:BoundField DataField="Description" HeaderText="Description" />
                <asp:BoundField DataField="Category" HeaderText="Category" />
                <asp:BoundField DataField="Price" HeaderText="Price" ApplyFormatInEditMode="true" DataFormatString="{0:c}" />
            </Fields>
        </asp:DetailsView>
        <br>
        
        <asp:GridView ID="grid" runat="server" DataSourceID="SqlDataSource1" 
            AutoGenerateColumns="False" 
            AutoGenerateEditButton="True" 
            AutoGenerateDeleteButton="True" 
            DataKeyNames="GameID">
            <Columns>
                <asp:BoundField DataField="GameID" HeaderText="Id"/>
                <asp:BoundField DataField="Name" HeaderText="Name" />
                <asp:BoundField DataField="Description" HeaderText="Description" />
                <asp:BoundField DataField="Category" HeaderText="Category" />
                <asp:BoundField DataField="Price" HeaderText="Price" ApplyFormatInEditMode="true" DataFormatString="{0:c}" />
            </Columns>
        </asp:GridView>
    </form>
</body>
</html>
